baseURL = 'https://jono-simple-blog.netlify.app/'
languageCode = 'en-us'
title = 'jono shields'
theme = 'archie'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params]
    mode="auto"
